# create with command:
# gcloud iam roles create dynatrace_function.cloud_function_deployment --project={PROJECT_ID} --file=dynatrace-gcp-function-cloud-function-deployment-role.yaml
title: Dynatrace GCP Function cloud function deployment role
description: Role for Dynatrace GCP function cloud function deployment
stage: GA
includedPermissions:
  - cloudfunctions.functions.call
  - cloudfunctions.functions.create
  - cloudfunctions.functions.get
  - cloudfunctions.functions.invoke
  - cloudfunctions.functions.list
  - cloudfunctions.functions.sourceCodeGet
  - cloudfunctions.functions.sourceCodeSet
  - cloudfunctions.functions.update
  - cloudfunctions.functions.getIamPolicy
  - cloudfunctions.locations.get
  - cloudfunctions.locations.list
  - cloudfunctions.operations.get
  - cloudfunctions.operations.list
  - cloudscheduler.locations.list
  - cloudscheduler.jobs.list
  - cloudscheduler.jobs.create
  - cloudscheduler.jobs.get
  - cloudscheduler.jobs.delete
  - appengine.applications.get
  - appengine.applications.create
  - pubsub.topics.list
  - pubsub.topics.create
  - pubsub.topics.update
  - pubsub.topics.getIamPolicy
  - pubsub.topics.setIamPolicy
  - secretmanager.secrets.list
  - secretmanager.versions.add
  - secretmanager.secrets.create
  - secretmanager.versions.list
  - secretmanager.secrets.getIamPolicy
  - secretmanager.secrets.setIamPolicy
  - resourcemanager.projects.get
  - resourcemanager.projects.getIamPolicy
  - resourcemanager.projects.setIamPolicy
  - serviceusage.services.enable
  - serviceusage.services.get
  - iam.serviceAccounts.actAs
  - iam.serviceAccounts.list
  - iam.serviceAccounts.create
  - iam.serviceAccounts.getIamPolicy
  - iam.serviceAccounts.setIamPolicy
  - iam.roles.list
  - iam.roles.create
  - iam.roles.update
  - monitoring.dashboards.list
  - monitoring.dashboards.create
