# Copyright 2021 Dynatrace LLC

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if or (eq .Values.deploymentType "logs") (eq .Values.deploymentType "all") }}
  {{- if eq .Values.activeGate.useExisting "false" }}
apiVersion: v1
kind: Service
metadata:
  name: dynatrace-activegate-gcpmon-clusterip
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: dynatrace-activegate-gcpmon
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
---
apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-activegate-gcpmon-pullsecret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-activegate-gcpmon-auth-token-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  auth-token: {{ template "activeGateAuthToken" . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dynatrace-activegate-gcpmon
  namespace: {{ .Release.Namespace }}
  labels:
    app: dynatrace-activegate-gcpmon
spec:
  selector:
    matchLabels:
      app: dynatrace-activegate-gcpmon
  replicas: 1
  serviceName: dynatrace-activegate-gcpmon
  template:
    metadata:
      labels:
        app: dynatrace-activegate-gcpmon
        envid: {{ template "environmentID" . }}
      annotations:
        "version": "1"
        checksum/config: {{ include (print $.Template.BasePath "/function-config.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/function-secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: dynatrace-activegate-gcpmon
          image: {{ template "activeGateImage" . }}
          imagePullPolicy: Always
          ports:
            - name: ag-port
              containerPort: 9999
          env:
            - name: DT_CAPABILITIES
              value: "log_analytics_collector"
            - name: DT_ID_SEED_NAMESPACE
              value: dynatrace 
            - name: DT_ID_SEED_PROJECT
              value: {{ .Values.gcpProjectId }}
            - name: DT_ID_SEED_ENV_ID
              value: {{ template "environmentID" . }}
            - name: DT_ID_SEED_CLUSTER_NAME
              value: {{ .Values.clusterName }}
            {{- if  or (eq .Values.useProxy "DT_ONLY") (eq .Values.useProxy "ALL") }}
            - name: DT_INTERNAL_PROXY
              valueFrom:
                configMapKeyRef:
                  name: dynatrace-gcp-monitor-config
              {{- if .Values.httpsProxy }}
                  key: HTTPS_PROXY
              {{- else }}
                  key: HTTP_PROXY
              {{- end }}
            {{- end }}
          volumeMounts:
            - name: dynatrace-activegate-gcpmon-auth-token-volume
              mountPath: /var/lib/dynatrace/secrets/tokens
          resources:
            requests:
              memory: 512Mi
              cpu: 1
            limits:
              memory: 1024Mi
              cpu: 1
          livenessProbe:
            httpGet:
              path: /rest/state
              port: 9999
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /rest/state
              port: 9999
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
      imagePullSecrets:
        - name: dynatrace-activegate-gcpmon-pullsecret
      volumes:
        - name: dynatrace-activegate-gcpmon-auth-token-volume
          secret:
            secretName: dynatrace-activegate-gcpmon-auth-token-secret
  updateStrategy:
    type: RollingUpdate
  {{- end }}
{{- end }}
