id: api
$schema: gcp_schema_v_1_0.json
version: 0.0.1
technology:
  name: Google Cloud APIs
minDynatraceVersion: 1.199
gcp:
- service: api
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.service
    id: service
  - value: resource.labels.method
    id: method
  - value: resource.labels.version
    id: version
  - value: resource.labels.location
    id: location
  metrics:
  - value: serviceruntime.googleapis.com/api/request_count
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_count
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.grpc_status_code
  - value: serviceruntime.googleapis.com/api/request_latencies
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_latencies
    type: gauge
    name: Request latencies
    unit: s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: serviceruntime.googleapis.com/api/request_latencies_backend
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_latencies_backend
    type: gauge
    name: Request backend latencies
    unit: s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: serviceruntime.googleapis.com/api/request_latencies_overhead
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_latencies_overhead
    type: gauge
    name: Request overhead latencies
    unit: s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: serviceruntime.googleapis.com/api/request_sizes
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_sizes
    type: gauge
    name: Request sizes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: serviceruntime.googleapis.com/api/response_sizes
    id: cloud.gcp.serviceruntime_googleapis_com.api.response_sizes
    type: gauge
    name: Response sizes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
dashboards:
  - dashboard: "dashboards/api.json"