id: apigee.googleapis.com/Environment
$schema: gcp_schema_v_1_0.json
version: 0.0.1
technology:
  name: Google Apigee Environment
minDynatraceVersion: 1.199
gcp:
- service: apigee.googleapis.com/Environment
  featureSet: default
  dimensions:
  - value: resource.labels.resource_container
    id: resource_container
  - value: resource.labels.org
    id: org
  - value: resource.labels.env
    id: env
  - value: resource.labels.location
    id: location
  metrics:
  - value: apigee.googleapis.com/environment/anomaly_count
    id: cloud.gcp.apigee_googleapis_com.environment.anomaly_count
    type: count,delta
    name: Apigee anomaly event count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.severity
    - value: metric.labels.direction
    - value: metric.labels.anomaly_type