id: autoscaler
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Autoscaler
gcp:
- service: autoscaler
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.location
    id: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    id: gcp.region
  - value: resource.labels.autoscaler_id
    id: autoscaler_id
  - value: resource.labels.autoscaler_name
    id: autoscaler_name
    compatibilityModeOnly: true
  - value: resource.labels.autoscaler_name
    id: gcp.instance.name
  - value: resource.labels.instance_group_manager_id
    id: instance_group_manager_id
  - value: resource.labels.instance_group_manager_name
    id: instance_group_manager_name
  metrics:
  - value: autoscaler.googleapis.com/capacity
    id: cloud.gcp.autoscaler_googleapis_com.capacity
    type: gauge
    name: Serving capacity
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.metric_type
  - value: autoscaler.googleapis.com/current_utilization
    id: cloud.gcp.autoscaler_googleapis_com.current_utilization
    type: gauge
    name: Current Autoscaler utilization
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.metric_type
