id: bigtable_cluster
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Bigtable Cluster
gcp:
- service: bigtable_cluster
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.instance
    id: instance
  - value: resource.labels.cluster
    id: cluster
  - value: resource.labels.zone
    id: zone
    compatibilityMode: true
  - value: resource.labels.zone
    id: gcp.region
  metrics:
  - value: bigtable.googleapis.com/cluster/cpu_load
    id: cloud.gcp.bigtable_googleapis_com.cluster.cpu_load
    type: gauge
    name: CPU load
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: bigtable.googleapis.com/cluster/cpu_load_hottest_node
    id: cloud.gcp.bigtable_googleapis_com.cluster.cpu_load_hottest_node
    type: gauge
    name: CPU load (hottest node)
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: bigtable.googleapis.com/cluster/disk_load
    id: cloud.gcp.bigtable_googleapis_com.cluster.disk_load
    type: gauge
    name: Disk load
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: bigtable.googleapis.com/cluster/node_count
    id: cloud.gcp.bigtable_googleapis_com.cluster.node_count
    type: gauge
    name: Nodes
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_type
  - value: bigtable.googleapis.com/cluster/storage_utilization
    id: cloud.gcp.bigtable_googleapis_com.cluster.storage_utilization
    type: gauge
    name: Storage utilization
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_type
  - value: bigtable.googleapis.com/disk/bytes_used
    id: cloud.gcp.bigtable_googleapis_com.disk.bytes_used
    type: gauge
    name: Data stored
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_type
  - value: bigtable.googleapis.com/disk/per_node_storage_capacity
    id: cloud.gcp.bigtable_googleapis_com.disk.per_node_storage_capacity
    type: gauge
    name: Storage capacity per node
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_type
  - value: bigtable.googleapis.com/disk/storage_capacity
    id: cloud.gcp.bigtable_googleapis_com.disk.storage_capacity
    type: gauge
    name: Storage capacity
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.storage_type
