id: cloudiot_device_registry
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud IoT Registry
gcp:
- service: cloudiot_device_registry
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.device_registry_id
    id: device_registry_id
  - value: resource.labels.location
    id: location
  metrics:
  - value: cloudiot.googleapis.com/device/active_devices
    id: cloud.gcp.cloudiot_googleapis_com.device.active_devices
    type: gauge
    name: Active devices
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.protocol
  - value: cloudiot.googleapis.com/device/billing_bytes_count
    id: cloud.gcp.cloudiot_googleapis_com.device.billing_bytes_count
    type: gauge
    name: Billable bytes transferred
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.direction
  - value: cloudiot.googleapis.com/device/error_count
    id: cloud.gcp.cloudiot_googleapis_com.device.error_count
    type: count,delta
    name: Errors communicating with devices
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.error
    - value: metric.labels.protocol
  - value: cloudiot.googleapis.com/device/operation_count
    id: cloud.gcp.cloudiot_googleapis_com.device.operation_count
    type: count,delta
    name: Operations
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.operation_type
  - value: cloudiot.googleapis.com/device/received_bytes_count
    id: cloud.gcp.cloudiot_googleapis_com.device.received_bytes_count
    type: count,delta
    name: Bytes received by devices
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: cloudiot.googleapis.com/device/sent_bytes_count
    id: cloud.gcp.cloudiot_googleapis_com.device.sent_bytes_count
    type: count,delta
    name: Bytes sent to devices
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
