id: cloud_run_revision
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Run Revision
gcp:
- service: cloud_run_revision
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.service_name
    id: service_name
  - value: resource.labels.revision_name
    id: revision_name
  - value: resource.labels.location
    id: location
    compatibilityMode: true
  - value: resource.labels.location
    id: gcp.region
  - value: resource.labels.configuration_name
    id: configuration_name
  metrics:
  - value: run.googleapis.com/container/billable_instance_time
    id: cloud.gcp.run_googleapis_com.container.billable_instance_time
    type: count,delta
    name: Billable Instance Time
    unit: s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: run.googleapis.com/container/cpu/allocation_time
    id: cloud.gcp.run_googleapis_com.container.cpu.allocation_time
    type: count,delta
    name: Container CPU Allocation
    unit: s{CPU}
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: run.googleapis.com/container/cpu/utilizations
    id: cloud.gcp.run_googleapis_com.container.cpu.utilizations
    type: gauge
    name: Container CPU Utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: run.googleapis.com/container/instance_count
    id: cloud.gcp.run_googleapis_com.container.instance_count
    type: gauge
    name: Instance Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.state
  - value: run.googleapis.com/container/max_request_concurrencies
    id: cloud.gcp.run_googleapis_com.container.max_request_concurrencies
    type: gauge
    name: Max Concurrent Requests
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.state
  - value: run.googleapis.com/container/memory/allocation_time
    id: cloud.gcp.run_googleapis_com.container.memory.allocation_time
    type: count,delta
    name: Container Memory Allocation
    unit: GiBy.s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: run.googleapis.com/container/memory/utilizations
    id: cloud.gcp.run_googleapis_com.container.memory.utilizations
    type: gauge
    name: Container Memory Utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: run.googleapis.com/container/network/received_bytes_count
    id: cloud.gcp.run_googleapis_com.container.network.received_bytes_count
    type: count,delta
    name: Received Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.kind
  - value: run.googleapis.com/container/network/sent_bytes_count
    id: cloud.gcp.run_googleapis_com.container.network.sent_bytes_count
    type: count,delta
    name: Sent Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.kind
  - value: run.googleapis.com/request_count
    id: cloud.gcp.run_googleapis_com.request_count
    type: count,delta
    name: Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.route
  - value: run.googleapis.com/request_latencies
    id: cloud.gcp.run_googleapis_com.request_latencies
    type: gauge
    name: Request Latency
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.route
alerts:
  - path: alerts/cloud_run_revision/cpu.utilizations.json
  - path: alerts/cloud_run_revision/memory.utilizations.json