id: cloud_function
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Function
gcp:
- service: cloud_function
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.function_name
    id: function_name
  - value: resource.labels.region
    id: region
  metrics:
  - value: cloudfunctions.googleapis.com/function/active_instances
    id: cloud.gcp.cloudfunctions_googleapis_com.function.active_instances
    type: gauge
    name: Active instances
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: cloudfunctions.googleapis.com/function/execution_count
    id: cloud.gcp.cloudfunctions_googleapis_com.function.execution_count
    type: count,delta
    name: Executions
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.status
    - value: metric.labels.trigger_type
  - value: cloudfunctions.googleapis.com/function/execution_times
    id: cloud.gcp.cloudfunctions_googleapis_com.function.execution_times
    type: gauge
    name: Execution times
    unit: ns
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.status
    - value: metric.labels.trigger_type
  - value: cloudfunctions.googleapis.com/function/network_egress
    id: cloud.gcp.cloudfunctions_googleapis_com.function.network_egress
    type: count,delta
    name: Network egress
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.trigger_type
  - value: cloudfunctions.googleapis.com/function/user_memory_bytes
    id: cloud.gcp.cloudfunctions_googleapis_com.function.user_memory_bytes
    type: gauge
    name: Memory usage
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.memory
    - value: metric.labels.trigger_type
dashboards:
  - dashboard: "dashboards/cloud_function.json"