id: cloudvolumesgcp-api.netapp.com_NetAppCloudVolumeSO
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google NetApp CVS-SO
gcp:
- service: cloudvolumesgcp-api.netapp.com_NetAppCloudVolumeSO
  featureSet: default
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.resource_container
    key: resource_container
  - value: resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    key: gcp.region
  - value: resource.labels.volume_id
    key: volume_id
    compatibilityModeOnly: true
  - value: resource.labels.volume_id
    key: gcp.instance.id
  metrics:
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/logical_bytes_backed_up
    key: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.logical_bytes_backed_up
    type: gauge
    name: NetApp CVS-SO Logical Bytes Backed Up
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/operation_count
    key: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.operation_count
    type: count,delta
    name: NetApp CVS-SO Operation Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.type
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/read_bytes_count
    key: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.read_bytes_count
    type: count,delta
    name: NetApp CVS-SO Read Bytes Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions: []
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/request_latencies
    key: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.request_latencies
    type: gauge
    name: NetApp CVS-SO Request Latencies
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.method
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/volume_size
    key: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.volume_size
    type: gauge
    name: NetApp CVS-SO Volume Size
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions: []
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/volume_usage
    key: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.volume_usage
    type: gauge
    name: NetApp CVS-SO Volume Usage
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: By
    dimensions:
    - value: metric.labels.type
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/write_bytes_count
    key: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.write_bytes_count
    type: count,delta
    name: NetApp CVS-SO Write Bytes Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: By
    dimensions: []