id: cloudml_job
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Cloud ML Job
gcp:
- service: cloudml_job
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.job_id
    id: job_id
  - value: resource.labels.region
    id: region
  metrics:
  - value: ml.googleapis.com/training/accelerator/memory/utilization
    id: cloud.gcp.ml_googleapis_com.training.accelerator.memory.utilization
    type: gauge
    name: Accelerator memory utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 360s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.task_type
    - value: metric.labels.task_index
    - value: metric.labels.trial_id
  - value: ml.googleapis.com/training/accelerator/utilization
    id: cloud.gcp.ml_googleapis_com.training.accelerator.utilization
    type: gauge
    name: Accelerator utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 360s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.task_type
    - value: metric.labels.task_index
    - value: metric.labels.trial_id
  - value: ml.googleapis.com/training/cpu/utilization
    id: cloud.gcp.ml_googleapis_com.training.cpu.utilization
    type: gauge
    name: CPU utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 360s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.task_type
    - value: metric.labels.task_index
    - value: metric.labels.trial_id
  - value: ml.googleapis.com/training/memory/utilization
    id: cloud.gcp.ml_googleapis_com.training.memory.utilization
    type: gauge
    name: Memory utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 360s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.task_type
    - value: metric.labels.task_index
    - value: metric.labels.trial_id
  - value: ml.googleapis.com/training/network/received_bytes_count
    id: cloud.gcp.ml_googleapis_com.training.network.received_bytes_count
    type: count,delta
    name: Network bytes received
    unit: By
    gcpOptions:
      ingestDelay: 360s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.task_type
    - value: metric.labels.task_index
    - value: metric.labels.trial_id
  - value: ml.googleapis.com/training/network/sent_bytes_count
    id: cloud.gcp.ml_googleapis_com.training.network.sent_bytes_count
    type: count,delta
    name: Network bytes sent
    unit: By
    gcpOptions:
      ingestDelay: 360s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.task_type
    - value: metric.labels.task_index
    - value: metric.labels.trial_id
