id: cloud_composer_environment
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Composer Environment
gcp:
- service: cloud_composer_environment
  featureSet: default
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  - value: resource.labels.location
    key: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    key: gcp.region
  - value: resource.labels.environment_name
    key: environment_name
    compatibilityModeOnly: true
  - value: resource.labels.environment_name
    key: gcp.instance.name
  metrics:
  - value: composer.googleapis.com/environment/api/request_count
    key: cloud.gcp.composer_googleapis_com.environment.api.request_count
    type: count,delta
    name: API Requests
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.api_version
    - value: metric.labels.api_method
  - value: composer.googleapis.com/environment/api/request_latencies
    key: cloud.gcp.composer_googleapis_com.environment.api.request_latencies
    type: gauge
    name: API Latency
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DISTRIBUTION
      metricKind: DELTA
      unit: ms
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.api_version
    - value: metric.labels.api_method
  - value: composer.googleapis.com/environment/dag_processing/parse_error_count
    key: cloud.gcp.composer_googleapis_com.environment.dag_processing.parse_error_count
    type: count,delta
    name: Parse Error Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/dag_processing/processes
    key: cloud.gcp.composer_googleapis_com.environment.dag_processing.processes
    type: gauge
    name: DAG parsing processes
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/dag_processing/processor_timeout_count
    key: cloud.gcp.composer_googleapis_com.environment.dag_processing.processor_timeout_count
    type: count,delta
    name: Processors Timeout Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/dag_processing/total_parse_time
    key: cloud.gcp.composer_googleapis_com.environment.dag_processing.total_parse_time
    type: gauge
    name: Total Parse Time
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: DOUBLE
      metricKind: GAUGE
      unit: s
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/dagbag_size
    key: cloud.gcp.composer_googleapis_com.environment.dagbag_size
    type: gauge
    name: Dag Bag Size
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/database_health
    key: cloud.gcp.composer_googleapis_com.environment.database_health
    type: gauge
    name: Database Healthy
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: BOOL
      metricKind: GAUGE
      unit: ''
    dimensions:
    - value: metric.labels.image_version
    - value: metric.labels.environment_type
  - value: composer.googleapis.com/environment/executor/open_slots
    key: cloud.gcp.composer_googleapis_com.environment.executor.open_slots
    type: gauge
    name: Executor Open Slots
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/executor/running_tasks
    key: cloud.gcp.composer_googleapis_com.environment.executor.running_tasks
    type: gauge
    name: Executor Running Tasks
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/finished_task_instance_count
    key: cloud.gcp.composer_googleapis_com.environment.finished_task_instance_count
    type: count,delta
    name: Task Instance Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.state
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/healthy
    key: cloud.gcp.composer_googleapis_com.environment.healthy
    type: gauge
    name: Healthy
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 300
      valueType: BOOL
      metricKind: GAUGE
      unit: ''
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/num_celery_workers
    key: cloud.gcp.composer_googleapis_com.environment.num_celery_workers
    type: gauge
    name: Celery Workers
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/scheduler_heartbeat_count
    key: cloud.gcp.composer_googleapis_com.environment.scheduler_heartbeat_count
    type: count,delta
    name: Scheduler Heartbeats
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/task_queue_length
    key: cloud.gcp.composer_googleapis_com.environment.task_queue_length
    type: gauge
    name: Task Queue Length
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
    - value: metric.labels.queue_name
  - value: composer.googleapis.com/environment/worker/pod_eviction_count
    key: cloud.gcp.composer_googleapis_com.environment.worker.pod_eviction_count
    type: count,delta
    name: Worker Pod Eviction Count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.image_version
  - value: composer.googleapis.com/environment/zombie_task_killed_count
    key: cloud.gcp.composer_googleapis_com.environment.zombie_task_killed_count
    type: count,delta
    name: Zombie Tasks Killed
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.image_version