id: cloud_dlp_project
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Cloud Data Loss Prevention Project
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
gcp:
- service: cloud_dlp_project
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.location
    id: location
  metrics:
  - value: dlp.googleapis.com/content_bytes_inspected_count
    id: cloud.gcp.dlp_googleapis_com.content_bytes_inspected_count
    type: count,delta
    name: Content bytes inspected
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: dlp.googleapis.com/content_bytes_transformed_count
    id: cloud.gcp.dlp_googleapis_com.content_bytes_transformed_count
    type: count,delta
    name: Content bytes transformed
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: dlp.googleapis.com/finding_count
    id: cloud.gcp.dlp_googleapis_com.finding_count
    type: count,delta
    name: Findings
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.info_type
  - value: dlp.googleapis.com/job_result_count
    id: cloud.gcp.dlp_googleapis_com.job_result_count
    type: count,delta
    name: Job results
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.success
  - value: dlp.googleapis.com/job_trigger_run_count
    id: cloud.gcp.dlp_googleapis_com.job_trigger_run_count
    type: count,delta
    name: Job trigger runs
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.job_type
  - value: dlp.googleapis.com/storage_bytes_inspected_count
    id: cloud.gcp.dlp_googleapis_com.storage_bytes_inspected_count
    type: count,delta
    name: Storage bytes inspected
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: dlp.googleapis.com/storage_bytes_transformed_count
    id: cloud.gcp.dlp_googleapis_com.storage_bytes_transformed_count
    type: count,delta
    name: Storage bytes transformed
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
