id: consumed_api
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Consumed API
gcp:
- service: consumed_api
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.service
    id: service
  - value: resource.labels.method
    id: method
  - value: resource.labels.version
    id: version
  - value: resource.labels.credential_id
    id: credential_id
  - value: resource.labels.location
    id: location
  metrics:
  - value: serviceruntime.googleapis.com/api/request_count
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_count
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.grpc_status_code
  - value: serviceruntime.googleapis.com/api/request_latencies
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_latencies
    type: gauge
    name: Request latencies
    unit: s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: serviceruntime.googleapis.com/api/request_sizes
    id: cloud.gcp.serviceruntime_googleapis_com.api.request_sizes
    type: gauge
    name: Request sizes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
  - value: serviceruntime.googleapis.com/api/response_sizes
    id: cloud.gcp.serviceruntime_googleapis_com.api.response_sizes
    type: gauge
    name: Response sizes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions: []
