id: datastore_request
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Cloud Datastore
gcp:
- service: datastore_request
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.module_id
    id: module_id
  - value: resource.labels.version_id
    id: version_id
  metrics:
  - value: datastore.googleapis.com/api/request_count
    id: cloud.gcp.datastore_googleapis_com.api.request_count
    type: count,delta
    name: Requests
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.api_method
    - value: metric.labels.response_code
  - value: datastore.googleapis.com/entity/read_sizes
    id: cloud.gcp.datastore_googleapis_com.entity.read_sizes
    type: gauge
    name: Sizes of read entities
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.type
  - value: datastore.googleapis.com/entity/write_sizes
    id: cloud.gcp.datastore_googleapis_com.entity.write_sizes
    type: gauge
    name: Sizes of written entities
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.op
  - value: datastore.googleapis.com/index/write_count
    id: cloud.gcp.datastore_googleapis_com.index.write_count
    type: count,delta
    name: Index writes
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: firestore.googleapis.com/api/request_count
    id: cloud.gcp.firestore_googleapis_com.api.request_count
    type: count,delta
    name: Requests
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.api_method
    - value: metric.labels.response_code
dashboards:
  - dashboard: "dashboards/datastore.json"