id: gae_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google App Engine Instance
gcp:
- service: gae_instance
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.module_id
    id: module_id
  - value: resource.labels.version_id
    id: version_id
  - value: resource.labels.instance_id
    id: instance_id
  - value: resource.labels.location
    id: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    id: gcp.region
  metrics:
  - value: appengine.googleapis.com/flex/instance/connections/current
    id: cloud.gcp.appengine_googleapis_com.flex.instance.connections.current
    type: gauge
    name: Connections
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/cpu/utilization
    id: cloud.gcp.appengine_googleapis_com.flex.instance.cpu.utilization
    type: gauge
    name: CPU Utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/network/received_bytes_count
    id: cloud.gcp.appengine_googleapis_com.flex.instance.network.received_bytes_count
    type: count,delta
    name: Network bytes received
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/network/sent_bytes_count
    id: cloud.gcp.appengine_googleapis_com.flex.instance.network.sent_bytes_count
    type: count,delta
    name: Network bytes sent
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/ws/avg_duration
    id: cloud.gcp.appengine_googleapis_com.flex.instance.ws.avg_duration
    type: gauge
    name: Websocket average duration
    unit: s
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
alerts:
  - path: alerts/gae_instance/cpu.utilization.json