id: gce_router
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Router
gcp:
- service: gce_router
  featureSet: default
  gcpMonitoringFilter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    key: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    key: gcp.project.id
  - value: resource.labels.router_id
    key: router_id
    compatibilityModeOnly: true
  - value: resource.labels.router_id
    key: gcp.instance.id
  - value: resource.labels.region
    key: region
    compatibilityModeOnly: true
  - value: resource.labels.region
    key: gcp.region
  metrics:
  - value: router.googleapis.com/best_received_routes_count
    key: cloud.gcp.router_googleapis_com.best_received_routes_count
    type: gauge
    name: Received routes count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: router.googleapis.com/bfd/control/receive_intervals
    key: cloud.gcp.router_googleapis_com.bfd.control.receive_intervals
    type: gauge
    name: BFD control packets receive intervals
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: ms
    dimensions:
    - value: metric.labels.peer_ip
  - value: router.googleapis.com/bfd/control/received_packets_count
    key: cloud.gcp.router_googleapis_com.bfd.control.received_packets_count
    type: count,delta
    name: Control packets received
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.peer_ip
  - value: router.googleapis.com/bfd/control/rejected_packets_count
    key: cloud.gcp.router_googleapis_com.bfd.control.rejected_packets_count
    type: count,delta
    name: Control packets rejected
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.peer_ip
  - value: router.googleapis.com/bfd/control/transmit_intervals
    key: cloud.gcp.router_googleapis_com.bfd.control.transmit_intervals
    type: gauge
    name: BFD control packets transmit intervals
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: ms
    dimensions:
    - value: metric.labels.peer_ip
  - value: router.googleapis.com/bfd/control/transmitted_packets_count
    key: cloud.gcp.router_googleapis_com.bfd.control.transmitted_packets_count
    type: count,delta
    name: Control packets transmitted
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: DELTA
      unit: '1'
    dimensions:
    - value: metric.labels.peer_ip
  - value: router.googleapis.com/bfd/session_up
    key: cloud.gcp.router_googleapis_com.bfd.session_up
    type: gauge
    name: BFD session status
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.peer_ip
  - value: router.googleapis.com/bgp/received_routes_count
    key: cloud.gcp.router_googleapis_com.bgp.received_routes_count
    type: gauge
    name: BGP received routes count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.bgp_peer_name
  - value: router.googleapis.com/bgp/sent_routes_count
    key: cloud.gcp.router_googleapis_com.bgp.sent_routes_count
    type: gauge
    name: BGP sent routes count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.bgp_peer_name
  - value: router.googleapis.com/bgp/session_up
    key: cloud.gcp.router_googleapis_com.bgp.session_up
    type: gauge
    name: BGP session status
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions:
    - value: metric.labels.bgp_peer_name
  - value: router.googleapis.com/bgp_sessions_down_count
    key: cloud.gcp.router_googleapis_com.bgp_sessions_down_count
    type: gauge
    name: BGP sessions down count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: router.googleapis.com/bgp_sessions_up_count
    key: cloud.gcp.router_googleapis_com.bgp_sessions_up_count
    type: gauge
    name: BGP sessions up count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: router.googleapis.com/router_up
    key: cloud.gcp.router_googleapis_com.router_up
    type: gauge
    name: Router status
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
  - value: router.googleapis.com/sent_routes_count
    key: cloud.gcp.router_googleapis_com.sent_routes_count
    type: gauge
    name: Sent routes count
    gcpOptions:
      ingestDelay: 180
      samplePeriod: 60
      valueType: INT64
      metricKind: GAUGE
      unit: '1'
    dimensions: []
