id: gce_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google VM Instance Firewall Insights
gcp:
- service: gce_instance
  featureSet: firewallinsights
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.instance_id
    id: instance_id
  - value: resource.labels.zone
    id: zone
    compatibilityModeOnly: true
  - value: resource.labels.zone
    id: gcp.region
  metrics:
  - value: firewallinsights.googleapis.com/vm/firewall_hit_count
    id: cloud.gcp.firewallinsights_googleapis_com.vm.firewall_hit_count
    type: count,delta
    name: VM Firewall Hit Counts
    unit: '1'
    gcpOptions:
      ingestDelay: 150s
      samplePeriod: 600s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.firewall_project_id
    - value: metric.labels.firewall_name
      id: firewall_name
      compatibilityModeOnly: true
    - value: metric.labels.firewall_name
      id: gcp.instance.name
  - value: firewallinsights.googleapis.com/vm/firewall_last_used_timestamp
    id: cloud.gcp.firewallinsights_googleapis_com.vm.firewall_last_used_timestamp
    type: gauge
    name: VM Firewall Last Used Timestamp
    unit: '1'
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 600s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.firewall_project_id
    - value: metric.labels.firewall_name
      id: firewall_name
      compatibilityModeOnly: true
    - value: metric.labels.firewall_name
      id: gcp.instance.name
      