id: gce_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google VM Instance
gcp:
- service: gce_instance
  featureSet: appenginee
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.instance_id
    id: instance_id
  - value: resource.labels.zone
    id: zone
    compatibilityModeOnly: true
  - value: resource.labels.zone
    id: gcp.region
  metrics:
  - value: appengine.googleapis.com/flex/autoscaler/connections/current
    id: cloud.gcp.appengine_googleapis_com.flex.autoscaler.connections.current
    type: gauge
    name: Writing and reading connections
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.service_id
    - value: metric.labels.state
    - value: metric.labels.version_id
    - value: metric.labels.instance_name
  - value: appengine.googleapis.com/flex/autoscaler/server/request_count
    id: cloud.gcp.appengine_googleapis_com.flex.autoscaler.server.request_count
    type: count,delta
    name: Request counts
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.service_id
    - value: metric.labels.version_id
    - value: metric.labels.instance_name