id: internal_http_lb_rule
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Internal HTTP/S Load Balancing Rule
gcp:
- service: internal_http_lb_rule
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.network_name
    id: network_name
  - value: resource.labels.region
    id: region
  - value: resource.labels.url_map_name
    id: url_map_name
  - value: resource.labels.forwarding_rule_name
    id: forwarding_rule_name
  - value: resource.labels.target_proxy_name
    id: target_proxy_name
  - value: resource.labels.matched_url_path_rule
    id: matched_url_path_rule
  - value: resource.labels.backend_target_name
    id: backend_target_name
  - value: resource.labels.backend_target_type
    id: backend_target_type
  - value: resource.labels.backend_name
    id: backend_name
  - value: resource.labels.backend_type
    id: backend_type
  - value: resource.labels.backend_scope
    id: backend_scope
  - value: resource.labels.backend_scope_type
    id: backend_scope_type
  metrics: 
  - value: loadbalancing.googleapis.com/https/internal/backend_latencies
    id: cloud.gcp.loadbalancing_googleapis_com.https.internal.backend_latencies
    type: gauge
    name: Backend latencies
    unit: ms
    gcpOptions:
      ingestDelay: 90s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/internal/request_bytes_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.internal.request_bytes_count
    type: count,delta
    name: Request bytes
    unit: By
    gcpOptions:
      ingestDelay: 90s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/internal/request_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.internal.request_count
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 90s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/internal/response_bytes_count
    id: cloud.gcp.loadbalancing_googleapis_com.https.internal.response_bytes_count
    type: count,delta
    name: Response bytes
    unit: By
    gcpOptions:
      ingestDelay: 90s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.cache_result
  - value: loadbalancing.googleapis.com/https/internal/total_latencies
    id: cloud.gcp.loadbalancing_googleapis_com.https.internal.total_latencies
    type: gauge
    name: Total latencies
    unit: ms
    gcpOptions:
      ingestDelay: 90s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.protocol
    - value: metric.labels.response_code
    - value: metric.labels.response_code_class
    - value: metric.labels.cache_result
dashboards:
  - dashboard: "dashboards/lb.json"