id: interconnect
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Interconnect
gcp:
- service: interconnect
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.interconnect
    id: interconnect
  metrics:
  - value: interconnect.googleapis.com/network/interconnect/capacity
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.capacity
    type: gauge
    name: Network Capacity
    unit: By/s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/dropped_packets_count
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.dropped_packets_count
    type: count,delta
    name: Dropped Packets
    unit: '{packets}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/link/operational
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.link.operational
    type: gauge
    name: Circuit Operational Status
    unit: ''
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: BOOL
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.link_id
  - value: interconnect.googleapis.com/network/interconnect/link/rx_power
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.link.rx_power
    type: gauge
    name: Circuit Receive Power
    unit: '{dBm}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.link_id
    - value: metric.labels.laser_index
  - value: interconnect.googleapis.com/network/interconnect/link/tx_power
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.link.tx_power
    type: gauge
    name: Circuit Transmit Power
    unit: '{dBm}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.link_id
    - value: metric.labels.laser_index
  - value: interconnect.googleapis.com/network/interconnect/operational
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.operational
    type: gauge
    name: Operational Status
    unit: ''
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: BOOL
      metricKind: GAUGE
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/receive_errors_count
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.receive_errors_count
    type: count,delta
    name: Ingress Errors
    unit: '{errors}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/received_bytes_count
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.received_bytes_count
    type: count,delta
    name: Ingress Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/received_unicast_packets_count
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.received_unicast_packets_count
    type: count,delta
    name: Ingress Unicast Packets
    unit: '{packets}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/send_errors_count
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.send_errors_count
    type: count,delta
    name: Egress Errors
    unit: '{errors}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/sent_bytes_count
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.sent_bytes_count
    type: count,delta
    name: Egress Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/interconnect/sent_unicast_packets_count
    id: cloud.gcp.interconnect_googleapis_com.network.interconnect.sent_unicast_packets_count
    type: count,delta
    name: Egress Unicast Packets
    unit: '{packets}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
