id: interconnect_attachment
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Interconnect Attachment
gcp:
- service: interconnect_attachment
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.attachment
    id: attachment
  - value: resource.labels.interconnect
    id: interconnect
  - value: resource.labels.region
    id: region
  - value: resource.labels.interconnect_project
    id: interconnect_project
  metrics:
  - value: interconnect.googleapis.com/network/attachment/capacity
    id: cloud.gcp.interconnect_googleapis_com.network.attachment.capacity
    type: gauge
    name: Network Capacity
    unit: By/s
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: interconnect.googleapis.com/network/attachment/received_bytes_count
    id: cloud.gcp.interconnect_googleapis_com.network.attachment.received_bytes_count
    type: count,delta
    name: Ingress Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/attachment/received_packets_count
    id: cloud.gcp.interconnect_googleapis_com.network.attachment.received_packets_count
    type: count,delta
    name: Ingress Packets
    unit: '{packets}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/attachment/sent_bytes_count
    id: cloud.gcp.interconnect_googleapis_com.network.attachment.sent_bytes_count
    type: count,delta
    name: Egress Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: interconnect.googleapis.com/network/attachment/sent_packets_count
    id: cloud.gcp.interconnect_googleapis_com.network.attachment.sent_packets_count
    type: count,delta
    name: Egress Packets
    unit: '{packets}'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
