id: istio_canonical_service
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Istio Canonical Service
gcp:
- service: istio_canonical_service
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.mesh_uid
    id: mesh_uid
  - value: resource.labels.namespace_name
    id: namespace_name
  - value: resource.labels.canonical_service_name
    id: canonical_service_name
  - value: resource.labels.location
    id: location
    compatibilityMode: true
  - value: resource.labels.location
    id: gcp.region
  - value: resource.labels.revision
    id: revision
  metrics:
  - value: istio.io/service/client/request_count
    id: cloud.gcp.istio_io.service.client.request_count
    type: count,delta
    name: Client Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/client/roundtrip_latencies
    id: cloud.gcp.istio_io.service.client.roundtrip_latencies
    type: gauge
    name: Client Roundtrip Latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/server/request_count
    id: cloud.gcp.istio_io.service.server.request_count
    type: count,delta
    name: Server Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/server/response_latencies
    id: cloud.gcp.istio_io.service.server.response_latencies
    type: gauge
    name: Server Response Latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
