id: k8s_container
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Kubernetes Container
gcp:
- service: k8s_container_istio
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.location
    id: location
  - value: resource.labels.cluster_name
    id: cluster_name
  - value: resource.labels.namespace_name
    id: namespace_name
  - value: resource.labels.pod_name
    id: pod_name
  - value: resource.labels.container_name
    id: container_name
  metrics:
  - value: istio.io/control/config_convergence_latencies
    id: cloud.gcp.istio_io.control.config_convergence_latencies
    type: gauge
    name: Config Convergence Latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.mesh_uid
    - value: metric.labels.revision
  - value: istio.io/control/config_event_count
    id: cloud.gcp.istio_io.control.config_event_count
    type: count,delta
    name: Config Event Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.mesh_uid
    - value: metric.labels.revision
    - value: metric.labels.operation
    - value: metric.labels.type
  - value: istio.io/control/config_push_count
    id: cloud.gcp.istio_io.control.config_push_count
    type: count,delta
    name: Config Push Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.mesh_uid
    - value: metric.labels.revision
    - value: metric.labels.success
    - value: metric.labels.type
  - value: istio.io/control/config_validation_count
    id: cloud.gcp.istio_io.control.config_validation_count
    type: count,delta
    name: Config Validation Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.mesh_uid
    - value: metric.labels.revision
    - value: metric.labels.success
    - value: metric.labels.type
  - value: istio.io/control/proxy_clients
    id: cloud.gcp.istio_io.control.proxy_clients
    type: gauge
    name: Proxy Clients
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.mesh_uid
    - value: metric.labels.revision
    - value: metric.labels.proxy_version
  - value: istio.io/control/rejected_config_count
    id: cloud.gcp.istio_io.control.rejected_config_count
    type: count,delta
    name: Rejected Config Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.mesh_uid
    - value: metric.labels.revision
    - value: metric.labels.type
  - value: istio.io/control/sidecar_injection_count
    id: cloud.gcp.istio_io.control.sidecar_injection_count
    type: count,delta
    name: Sidecar Injection Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.mesh_uid
    - value: metric.labels.revision
    - value: metric.labels.success
  - value: istio.io/service/server/connection_close_count
    id: cloud.gcp.istio_io.service.server.connection_close_count
    type: count,delta
    name: Server Connection Close Count
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
  - value: istio.io/service/server/connection_open_count
    id: cloud.gcp.istio_io.service.server.connection_open_count
    type: count,delta
    name: Server Connection Open Count
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
  - value: istio.io/service/server/received_bytes_count
    id: cloud.gcp.istio_io.service.server.received_bytes_count
    type: count,delta
    name: Server Received Bytes Count
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
  - value: istio.io/service/server/request_bytes
    id: cloud.gcp.istio_io.service.server.request_bytes
    type: gauge
    name: Server Request Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/server/request_count
    id: cloud.gcp.istio_io.service.server.request_count
    type: count,delta
    name: Server Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/server/response_bytes
    id: cloud.gcp.istio_io.service.server.response_bytes
    type: gauge
    name: Server Response Bytes
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/server/response_latencies
    id: cloud.gcp.istio_io.service.server.response_latencies
    type: gauge
    name: Server Response Latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision
    - value: metric.labels.request_operation
    - value: metric.labels.api_version
    - value: metric.labels.response_code
    - value: metric.labels.api_name
  - value: istio.io/service/server/sent_bytes_count
    id: cloud.gcp.istio_io.service.server.sent_bytes_count
    type: count,delta
    name: Server Sent Bytes Count
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.request_protocol
    - value: metric.labels.service_authentication_policy
    - value: metric.labels.mesh_uid
    - value: metric.labels.destination_service_name
    - value: metric.labels.destination_service_namespace
    - value: metric.labels.destination_port
    - value: metric.labels.source_principal
    - value: metric.labels.source_workload_name
    - value: metric.labels.source_workload_namespace
    - value: metric.labels.source_owner
    - value: metric.labels.destination_principal
    - value: metric.labels.destination_workload_name
    - value: metric.labels.destination_workload_namespace
    - value: metric.labels.destination_owner
    - value: metric.labels.source_canonical_service_name
    - value: metric.labels.destination_canonical_service_name
    - value: metric.labels.source_canonical_service_namespace
    - value: metric.labels.destination_canonical_service_namespace
    - value: metric.labels.source_canonical_revision
    - value: metric.labels.destination_canonical_revision