id: k8s_pod
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Kubernetes Pod
gcp:
- service: k8s_pod
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.location
    id: location
    compatibilityMode: true
  - value: resource.labels.location
    id: gcp.region
  - value: resource.labels.cluster_name
    id: cluster_name
  - value: resource.labels.namespace_name
    id: namespace_name
  - value: resource.labels.pod_name
    id: pod_name
    compatibilityMode: false
  - value: resource.labels.pod_name
    id: gcp.instance.name
  metrics:
  - value: kubernetes.io/pod/network/received_bytes_count
    id: cloud.gcp.kubernetes_io.pod.network.received_bytes_count
    type: count,delta
    name: Bytes received
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions: []
  - value: kubernetes.io/pod/network/sent_bytes_count
    id: cloud.gcp.kubernetes_io.pod.network.sent_bytes_count
    type: count,delta
    name: Bytes transmitted
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions: []
  - value: kubernetes.io/pod/volume/total_bytes
    id: cloud.gcp.kubernetes_io.pod.volume.total_bytes
    type: gauge
    name: Volume capacity
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.volume_name
  - value: kubernetes.io/pod/volume/used_bytes
    id: cloud.gcp.kubernetes_io.pod.volume.used_bytes
    type: gauge
    name: Volume usage
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.volume_name
  - value: kubernetes.io/pod/volume/utilization
    id: cloud.gcp.kubernetes_io.pod.volume.utilization
    type: gauge
    name: Volume utilization
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.volume_name
