id: k8s_node
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Kubernetes Node
gcp:
- service: k8s_node
  dimensions:
  - value: resource.labels.project_id
    id: project_id  
  - value: resource.labels.location
    id: location
  - value: resource.labels.cluster_name
    id: cluster_name
  - value: resource.labels.node_name
    id: node_name
  metrics:
  - value: kubernetes.io/node/cpu/allocatable_cores
    id: cloud.gcp.kubernetes_io.node.cpu.allocatable_cores
    type: gauge
    name: Allocatable cores
    unit: '{cpu}'
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/cpu/allocatable_utilization
    id: cloud.gcp.kubernetes_io.node.cpu.allocatable_utilization
    type: gauge
    name: CPU allocatable utilization
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/cpu/core_usage_time
    id: cloud.gcp.kubernetes_io.node.cpu.core_usage_time
    type: count,delta
    name: CPU usage time
    unit: s{CPU}
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: CUMULATIVE
    dimensions: []
  - value: kubernetes.io/node/cpu/total_cores
    id: cloud.gcp.kubernetes_io.node.cpu.total_cores
    type: gauge
    name: Total cores
    unit: '{cpu}'
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/ephemeral_storage/allocatable_bytes
    id: cloud.gcp.kubernetes_io.node.ephemeral_storage.allocatable_bytes
    type: gauge
    name: Allocatable ephemeral storage
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/ephemeral_storage/inodes_free
    id: cloud.gcp.kubernetes_io.node.ephemeral_storage.inodes_free
    type: gauge
    name: Free inodes
    unit: '1'
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/ephemeral_storage/inodes_total
    id: cloud.gcp.kubernetes_io.node.ephemeral_storage.inodes_total
    type: gauge
    name: Total inodes
    unit: '1'
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/ephemeral_storage/total_bytes
    id: cloud.gcp.kubernetes_io.node.ephemeral_storage.total_bytes
    type: gauge
    name: Total ephemeral storage
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/ephemeral_storage/used_bytes
    id: cloud.gcp.kubernetes_io.node.ephemeral_storage.used_bytes
    type: gauge
    name: Ephemeral storage usage
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/memory/allocatable_bytes
    id: cloud.gcp.kubernetes_io.node.memory.allocatable_bytes
    type: gauge
    name: Allocatable memory
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/memory/allocatable_utilization
    id: cloud.gcp.kubernetes_io.node.memory.allocatable_utilization
    type: gauge
    name: Memory allocatable utilization
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.memory_type
    - value: metric.labels.component
  - value: kubernetes.io/node/memory/total_bytes
    id: cloud.gcp.kubernetes_io.node.memory.total_bytes
    type: gauge
    name: Total memory
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/memory/used_bytes
    id: cloud.gcp.kubernetes_io.node.memory.used_bytes
    type: gauge
    name: Memory usage
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.memory_type
  - value: kubernetes.io/node/network/received_bytes_count
    id: cloud.gcp.kubernetes_io.node.network.received_bytes_count
    type: count,delta
    name: Bytes received
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions: []
  - value: kubernetes.io/node/network/sent_bytes_count
    id: cloud.gcp.kubernetes_io.node.network.sent_bytes_count
    type: count,delta
    name: Bytes transmitted
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions: []
  - value: kubernetes.io/node/pid_limit
    id: cloud.gcp.kubernetes_io.node.pid_limit
    type: gauge
    name: PID capacity
    unit: '1'
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node/pid_used
    id: cloud.gcp.kubernetes_io.node.pid_used
    type: gauge
    name: PID usage
    unit: '1'
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: kubernetes.io/node_daemon/cpu/core_usage_time
    id: cloud.gcp.kubernetes_io.node_daemon.cpu.core_usage_time
    type: count,delta
    name: CPU usage time
    unit: s{CPU}
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.component
  - value: kubernetes.io/node_daemon/memory/used_bytes
    id: cloud.gcp.kubernetes_io.node_daemon.memory.used_bytes
    type: gauge
    name: Memory usage
    unit: By
    gcpOptions:
      ingestDelay: 0s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.component
    - value: metric.labels.memory_type
