id: knative_broker
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Cloud Run for Anthos Broker
gcp:
- service: knative_broker
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.location
    id: location
  - value: resource.labels.cluster_name
    id: cluster_name
  - value: resource.labels.namespace_name
    id: namespace_name
  - value: resource.labels.broker_name
    id: broker_name
  metrics: 
  - value: knative.dev/eventing/broker/event_count
    id: cloud.gcp.knative_dev.eventing.broker.event_count
    type: count,delta
    name: Broker Event Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code_class
    - value: metric.labels.response_code
    - value: metric.labels.event_type
  - value: knative.dev/internal/eventing/broker/event_count
    id: cloud.gcp.knative_dev.internal.eventing.broker.event_count
    type: count,delta
    name: Write Only Broker Event Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.container_name
    - value: metric.labels.pod_name
    - value: metric.labels.response_code_class
    - value: metric.labels.response_code
    - value: metric.labels.event_type
