id: knative_broker
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Run for Anthos Broker
gcp:
- service: knative_broker
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.location
    id: location
    compatibilityMode: true
  - value: resource.labels.location
    id: gcp.region
  - value: resource.labels.cluster_name
    id: cluster_name
  - value: resource.labels.namespace_name
    id: namespace_name
  - value: resource.labels.broker_name
    id: broker_name
    compatibilityMode: true
  - value: resource.labels.broker_name
    id: gcp.instance.name
  metrics: 
  - value: knative.dev/eventing/broker/event_count
    id: cloud.gcp.knative_dev.eventing.broker.event_count
    type: count,delta
    name: Broker Event Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code_class
    - value: metric.labels.response_code
    - value: metric.labels.event_type
  - value: knative.dev/internal/eventing/broker/event_count
    id: cloud.gcp.knative_dev.internal.eventing.broker.event_count
    type: count,delta
    name: Write Only Broker Event Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.container_name
    - value: metric.labels.pod_name
    - value: metric.labels.response_code_class
    - value: metric.labels.response_code
    - value: metric.labels.event_type
