id: microsoft_ad_domain
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud Microsoft Active Directory Domain
gcp:
- service: microsoft_ad_domain
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityModeOnly: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.fqdn
    id: fqdn
  - value: resource.labels.location
    id: location
    compatibilityModeOnly: true
  - value: resource.labels.location
    id: gcp.region
  metrics:
  - value: managedidentities.googleapis.com/microsoft_ad/domain/health
    id: cloud.gcp.managedidentities_googleapis_com.microsoft_ad.domain.health
    type: gauge
    name: AD Domain Health
    unit: ''
    gcpOptions:
      ingestDelay: 195s
      samplePeriod: 60s
      valueType: BOOL
      metricKind: GAUGE
    dimensions: []
  - value: managedidentities.googleapis.com/microsoft_ad/domain/trust/state
    id: cloud.gcp.managedidentities_googleapis_com.microsoft_ad.domain.trust.state
    type: gauge
    name: AD Domain Trust Health
    unit: ''
    gcpOptions:
      ingestDelay: 165s
      samplePeriod: 60s
      valueType: BOOL
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.trust_direction
    - value: metric.labels.target_domain_name
      id: target_domain_name
      compatibilityModeOnly: true
    - value: metric.labels.target_domain_name
      id: gcp.instance.name
    - value: metric.labels.trust_type
