id: nat_gateway
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud NAT Gateway
gcp:
- service: nat_gateway
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.region
    id: region
    compatibilityMode: true
  - value: resource.labels.region
    id: gcp.region
  - value: resource.labels.router_id
    id: router_id
  - value: resource.labels.gateway_name
    id: gateway_name
  metrics:
  - value: router.googleapis.com/nat/allocated_ports
    id: cloud.gcp.router_googleapis_com.nat.allocated_ports
    type: gauge
    name: Allocated ports
    unit: '{port}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.nat_ip
  - value: router.googleapis.com/nat/closed_connections_count
    id: cloud.gcp.router_googleapis_com.nat.closed_connections_count
    type: count,delta
    name: Closed connections count
    unit: '{connection}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/dropped_received_packets_count
    id: cloud.gcp.router_googleapis_com.nat.dropped_received_packets_count
    type: count,delta
    name: Received packets dropped count
    unit: '{packet}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/dropped_sent_packets_count
    id: cloud.gcp.router_googleapis_com.nat.dropped_sent_packets_count
    type: count,delta
    name: Sent packets dropped count
    unit: '{packet}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
    - value: metric.labels.reason
  - value: router.googleapis.com/nat/nat_allocation_failed
    id: cloud.gcp.router_googleapis_com.nat.nat_allocation_failed
    type: gauge
    name: NAT allocation failed
    unit: ''
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: BOOL
      metricKind: GAUGE
    dimensions: []
  - value: router.googleapis.com/nat/new_connections_count
    id: cloud.gcp.router_googleapis_com.nat.new_connections_count
    type: count,delta
    name: New connections count
    unit: '{connection}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/open_connections
    id: cloud.gcp.router_googleapis_com.nat.open_connections
    type: gauge
    name: Open connections
    unit: '{connection}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/port_usage
    id: cloud.gcp.router_googleapis_com.nat.port_usage
    type: gauge
    name: Port usage
    unit: '{port}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/received_bytes_count
    id: cloud.gcp.router_googleapis_com.nat.received_bytes_count
    type: count,delta
    name: Received bytes count
    unit: By
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/received_packets_count
    id: cloud.gcp.router_googleapis_com.nat.received_packets_count
    type: count,delta
    name: Received packets count
    unit: '{packet}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/sent_bytes_count
    id: cloud.gcp.router_googleapis_com.nat.sent_bytes_count
    type: count,delta
    name: Sent bytes count
    unit: By
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
  - value: router.googleapis.com/nat/sent_packets_count
    id: cloud.gcp.router_googleapis_com.nat.sent_packets_count
    type: count,delta
    name: Sent packets count
    unit: '{packet}'
    gcpOptions:
      ingestDelay: 225s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.ip_protocol
