id: network_security_policy
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Network Security Policy
gcp:
- service: network_security_policy
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.policy_name
    id: policy_name
  metrics:
  - value: networksecurity.googleapis.com/https/previewed_request_count
    id: cloud.gcp.networksecurity_googleapis_com.https.previewed_request_count
    type: count,delta
    name: Previewed request count
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.blocked
    - value: metric.labels.backend_target_name
  - value: networksecurity.googleapis.com/https/request_count
    id: cloud.gcp.networksecurity_googleapis_com.https.request_count
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.blocked
    - value: metric.labels.backend_target_name
