id: pubsublite_subscription_partition
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Pub/Sub Lite Subscription Partition
gcp:
- service: pubsublite_subscription_partition
  featureSet: default
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.subscription_id
    id: subscription_id
  - value: resource.labels.partition
    id: partition
  - value: resource.labels.location
    id: location
  metrics:
  - value: pubsublite.googleapis.com/subscription/backlog_message_count
    id: cloud.gcp.pubsublite_googleapis_com.subscription.backlog_message_count
    type: gauge
    name: Backlog message count
    unit: '1'
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/subscription/backlog_quota_bytes
    id: cloud.gcp.pubsublite_googleapis_com.subscription.backlog_quota_bytes
    type: gauge
    name: Backlog quota bytes
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/subscription/oldest_unacked_message_age
    id: cloud.gcp.pubsublite_googleapis_com.subscription.oldest_unacked_message_age
    type: gauge
    name: Oldest unacked message age
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/subscription/sent_message_count
    id: cloud.gcp.pubsublite_googleapis_com.subscription.sent_message_count
    type: count,delta
    name: Subscription sent message count
    unit: '1'
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: pubsublite.googleapis.com/subscription/sent_quota_bytes
    id: cloud.gcp.pubsublite_googleapis_com.subscription.sent_quota_bytes
    type: count,delta
    name: Subscription sent quota bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: pubsublite.googleapis.com/subscription/sent_raw_bytes
    id: cloud.gcp.pubsublite_googleapis_com.subscription.sent_raw_bytes
    type: count,delta
    name: Subscription sent raw bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
dashboards:
  - dashboard: "dashboards/pubsub.json"