id: pubsublite_topic_partition
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Pub/Sub Lite Topic Partition
gcp:
- service: pubsublite_topic_partition
  featureSet: default
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.topic_id
    id: topic_id
  - value: resource.labels.partition
    id: partition
  - value: resource.labels.location
    id: location
  metrics:
  - value: pubsublite.googleapis.com/topic/oldest_retained_message_age
    id: cloud.gcp.pubsublite_googleapis_com.topic.oldest_retained_message_age
    type: gauge
    name: Oldest retained message age
    unit: s
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/topic/publish_message_count
    id: cloud.gcp.pubsublite_googleapis_com.topic.publish_message_count
    type: count,delta
    name: Publish message count
    unit: '1'
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: pubsublite.googleapis.com/topic/publish_quota_byte_limit
    id: cloud.gcp.pubsublite_googleapis_com.topic.publish_quota_byte_limit
    type: gauge
    name: Publish quota byte limit
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/topic/publish_quota_bytes
    id: cloud.gcp.pubsublite_googleapis_com.topic.publish_quota_bytes
    type: count,delta
    name: Publish quota bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: pubsublite.googleapis.com/topic/publish_quota_utilization
    id: cloud.gcp.pubsublite_googleapis_com.topic.publish_quota_utilization
    type: gauge
    name: Publish quota utilization ratio
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/topic/publish_raw_bytes
    id: cloud.gcp.pubsublite_googleapis_com.topic.publish_raw_bytes
    type: count,delta
    name: Publish raw bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: pubsublite.googleapis.com/topic/publish_request_count
    id: cloud.gcp.pubsublite_googleapis_com.topic.publish_request_count
    type: count,delta
    name: Publish request count
    unit: '1'
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.response_code
  - value: pubsublite.googleapis.com/topic/sent_quota_bytes
    id: cloud.gcp.pubsublite_googleapis_com.topic.sent_quota_bytes
    type: count,delta
    name: Topic sent quota bytes
    unit: By
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: pubsublite.googleapis.com/topic/storage_quota_byte_limit
    id: cloud.gcp.pubsublite_googleapis_com.topic.storage_quota_byte_limit
    type: gauge
    name: Storage quota byte limit
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/topic/subscribe_quota_byte_limit
    id: cloud.gcp.pubsublite_googleapis_com.topic.subscribe_quota_byte_limit
    type: gauge
    name: Subscribe quota byte limit
    unit: By
    gcpOptions:
      ingestDelay: 120s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: pubsublite.googleapis.com/topic/subscribe_quota_utilization
    id: cloud.gcp.pubsublite_googleapis_com.topic.subscribe_quota_utilization
    type: gauge
    name: Subscribe quota utilization ratio
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 210s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
dashboards:
  - dashboard: "dashboards/pubsub.json"