id: recaptchaenterprise.googleapis.com/Key
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google reCAPTCHA Key
gcp:
- service: recaptchaenterprise.googleapis.com/Key
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.resource_container
    id: resource_container
  - value: resource.labels.location
    id: location
    compatibilityMode: true
  - value: resource.labels.location
    id: gcp.region
  - value: resource.labels.key_id
    id: key_id
  metrics: 
  - value: recaptchaenterprise.googleapis.com/score_counts
    id: cloud.gcp.recaptchaenterprise_googleapis_com.score_counts
    type: gauge
    name: Score counts
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.action
