id: tpu_worker
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
vars:
 - id: filter_conditions
   displayName: Metric query filter for which metrics should be queried
   type: variables
technology:
  name: Google Cloud TPU Worker
gcp:
- service: tpu_worker
  featureSet: default
  gcp_monitoring_filter: var:filter_conditions
  dimensions:
  - value: resource.labels.project_id
    id: project_id
    compatibilityMode: true
  - value: resource.labels.project_id
    id: gcp.project.id
  - value: resource.labels.zone
    id: zone
  - value: resource.labels.node_id
    id: node_id
  - value: resource.labels.worker_id
    id: worker_id
  metrics:
  - value: tpu.googleapis.com/container/cpu/utilization
    id: cloud.gcp.tpu_googleapis_com.container.cpu.utilization
    type: gauge
    name: Container CPU utilization
    unit: '%'
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.container_name
  - value: tpu.googleapis.com/container/memory/usage
    id: cloud.gcp.tpu_googleapis_com.container.memory.usage
    type: gauge
    name: Container memory usage
    unit: By
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.container_name
  - value: tpu.googleapis.com/cpu/utilization
    id: cloud.gcp.tpu_googleapis_com.cpu.utilization
    type: gauge
    name: CPU utilization
    unit: '%'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.core
  - value: tpu.googleapis.com/memory/usage
    id: cloud.gcp.tpu_googleapis_com.memory.usage
    type: gauge
    name: Memory usage
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: tpu.googleapis.com/network/received_bytes_count
    id: cloud.gcp.tpu_googleapis_com.network.received_bytes_count
    type: count,delta
    name: Network bytes received
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: tpu.googleapis.com/network/sent_bytes_count
    id: cloud.gcp.tpu_googleapis_com.network.sent_bytes_count
    type: count,delta
    name: Network bytes sent
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: tpu.googleapis.com/tpu/mxu/utilization
    id: cloud.gcp.tpu_googleapis_com.tpu.mxu.utilization
    type: gauge
    name: MXU utilization
    unit: '%'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
